// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CopyRule } from "./CopyRule";
import type { DatabaseSpec } from "./DatabaseSpec";
import type { Defaults } from "./Defaults";
import type { EnvFile } from "./EnvFile";
import type { PortSpec } from "./PortSpec";
import type { ServiceSpec } from "./ServiceSpec";
import type { SetupStep } from "./SetupStep";
import type { WorktreeSpec } from "./WorktreeSpec";

/**
 * # canopy.yaml
 *
 * A repository's whole development environment: the ports each worktree gets, the commands
 * that provision it, the long-running services, and where the worktree itself goes.
 */
export type CanopyConfig = { 
/**
 * Only `1` exists. Present so a future format can be recognised rather than guessed at.
 */
version: number, 
/**
 * The project name, used by `${project.name}`. Defaults to the repository directory name.
 */
name?: string | null, 
/**
 * Settings every service inherits unless it overrides them.
 */
defaults: Defaults, 
/**
 * Project-wide env, layered under every service and setup step.
 */
env: { [key in string]: string }, 
/**
 * Named ports. Each worktree gets its own free number for each name.
 */
ports: { [key in string]: PortSpec }, 
/**
 * Database forks. Parsed but not yet acted on; `config check` warns.
 */
databases: { [key in string]: DatabaseSpec }, 
/**
 * Commands run once when a worktree is provisioned, in order.
 */
setup: Array<SetupStep>, 
/**
 * Long-running processes `canopyd up` starts and supervises.
 */
services: { [key in string]: ServiceSpec }, 
/**
 * Dotenv written into each worktree with everything resolved; `false` disables it.
 */
env_file: EnvFile, 
/**
 * Where worktrees go and what they branch from.
 */
worktree: WorktreeSpec, 
/**
 * Gitignored files carried from the source checkout into a new worktree.
 */
copy: Array<CopyRule>, };
