// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A setup step. `setup: [npm ci]` and the object form both land here — the bare string is the
 * overwhelmingly common case and making people write `- run:` for it would be noise.
 *
 * Serialized — by `canopyd config show --json`, and so by the TypeScript binding — a step is
 * always the object form, since that is the normalised one.
 */
export type SetupStep = { 
/**
 * Shell command, run through `/bin/sh -c` in the worktree.
 */
run: string, 
/**
 * For logs and `--only`. Defaults to `step 1`, `step 2`, …
 */
name: string | null, 
/**
 * Relative to the worktree root; created if absent.
 */
cwd: string | null, 
/**
 * On top of the resolved environment.
 */
env: { [key in string]: string }, 
/**
 * Skip when these files have the same content as in the source checkout.
 */
if_changed: Array<string> | null, };
