//! A worktree's environment: `${…}` substitution, the layering order, and the dotenv on disk.
//!
//! Port of `packages/daemon/src/env/config/resolve.ts`. Every rule about *which* value a
//! service ends up seeing lives here and nowhere else, because "why does my service see this?"
//! must have exactly one answer — and because a preview (`canopyd env`) has to show the same
//! table the supervisor will hand to `execve`.
//!
//! Three decisions are worth their reasons up front.
//!
//! **Substitution is single-pass.** What a substitution inserts is never rescanned. Values come
//! from branch names, from the ambient environment and from a `canopy.yaml` several people
//! share; if the result of `${worktree.branch}` were scanned again, a branch called
//! `wip/${db.main.url}` would read someone else's credentials into a variable. One pass makes
//! substituted text data, permanently.
//!
//! **An unresolvable reference is left verbatim, never blanked and never an error.**
//! `${CANOPY_HOME}` and `$(cat secret)` are shell — `run:` goes to `/bin/sh -c`, so they must
//! survive untouched — and `${db.main.url}` names a database fork this crate does not create
//! yet. Blanking turns a typo into an empty connection string that fails a mile downstream;
//! erroring refuses to run a file the daemon runs fine.
//!
//! **Masking is presentation.** [`EnvTable::masked`] exists for a screen and a JSON payload. The
//! dotenv, `--export` and the child's environment carry the real values, because the point of
//! the table is to make a process work.

use std::collections::BTreeMap;
use std::fs;

use camino::{Utf8Path, Utf8PathBuf};
use serde::Serialize;

use crate::config::{CanopyConfig, TemplateRef, template_refs};

/// What [`EnvTable::masked`] shows instead of a secret. Fixed-width on purpose: a mask whose
/// length tracked the value would leak the length.
pub const MASK: &str = "********";

/// Written at the top of every generated dotenv, since the file is overwritten on every
/// provision and hand edits would vanish without a word.
const DOTENV_HEADER: &str = "# generated by canopy — do not edit";

/// Key substrings that make a variable a secret whatever its value looks like.
const SECRET_WORDS: [&str; 8] = ["SECRET", "TOKEN", "PASSWORD", "PASSWD", "APIKEY", "API_KEY", "PRIVATE", "CREDENTIAL"];

// ---------------------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------------------

/// Module-local: writing a dotenv is the only thing here that can fail, and the crate's `Error`
/// does not need a variant for it.
#[derive(Debug, thiserror::Error)]
pub enum EnvError {
    #[error("cannot write {path}: {source}")]
    Write {
        path: Utf8PathBuf,
        #[source]
        source: std::io::Error,
    },
}

// ---------------------------------------------------------------------------------------
// The table
// ---------------------------------------------------------------------------------------

/// Which layer had the last word on a variable. Kept per variable rather than recomputed,
/// because the answer to "why is this value what it is" is the layer, not the value.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum EnvSource {
    /// Canopy's own facts: `CANOPY_WORKTREE`, `CANOPY_PORT_*`, …
    Canopy,
    /// `defaults.env` in `canopy.yaml`.
    Defaults,
    /// Top-level `env:` in `canopy.yaml`.
    Config,
    /// Handed in by the caller — a `--env` flag, a saved per-worktree setting.
    Override,
    /// A database fork's URL, under the variable its spec names.
    Database,
    /// A service's own `env:`.
    Service,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize)]
pub struct EnvVar {
    pub key: String,
    /// Already substituted. No consumer should ever see a `${…}` it is expected to resolve.
    pub value: String,
    pub secret: bool,
    pub source: EnvSource,
}

/// The resolved environment, in the order the keys first appeared.
///
/// Insertion order, not sorted order, because it reads as the layering: Canopy's facts, then
/// the file, then the overrides. A later layer overwriting a key updates it in place rather
/// than moving it to the end, so the table does not reshuffle when someone adds an override.
/// Anything written to disk sorts instead — see [`EnvTable::to_dotenv`].
#[derive(Debug, Clone, Default, PartialEq, Eq, Serialize)]
#[serde(transparent)]
pub struct EnvTable {
    vars: Vec<EnvVar>,
}

impl EnvTable {
    pub fn get(&self, key: &str) -> Option<&str> {
        self.vars.iter().find(|var| var.key == key).map(|var| var.value.as_str())
    }

    pub fn vars(&self) -> &[EnvVar] {
        &self.vars
    }

    /// The table as a plain map, ready for a process spawn.
    pub fn to_map(&self) -> BTreeMap<String, String> {
        self.vars.iter().map(|var| (var.key.clone(), var.value.clone())).collect()
    }

    /// The table with secret values replaced by [`MASK`] — for a terminal or a JSON payload.
    ///
    /// A separate method rather than a flag on the table: masking that could be forgotten on
    /// the way *in* would corrupt what we write to disk. This way the stored value is always
    /// the real one and only the caller that is about to display something asks for the mask.
    pub fn masked(&self) -> Vec<EnvVar> {
        self.vars
            .iter()
            .map(|var| if var.secret { EnvVar { value: MASK.to_owned(), ..var.clone() } } else { var.clone() })
            .collect()
    }

    /// The generated dotenv, byte-for-byte deterministic.
    ///
    /// Sorted by key so the same inputs produce the same file no matter what order the caller
    /// assembled them in: the file lands in a worktree that may be under version control and
    /// is rewritten on every provision, and a diff that is sometimes a reshuffle is a diff
    /// nobody reads.
    pub fn to_dotenv(&self) -> String {
        let mut out = String::from(DOTENV_HEADER);
        out.push('\n');
        for (key, value) in self.to_map() {
            out.push_str(&key);
            out.push('=');
            out.push_str(&dotenv_value(&value));
            out.push('\n');
        }
        out
    }

    /// `export K='v'` lines for `eval "$(canopyd env --export)"`.
    ///
    /// Always single-quoted, even when the dotenv would not bother: this text is fed straight
    /// to a shell, so there is no reader to be lenient for and nothing to gain from bareness.
    pub fn to_export(&self) -> String {
        let mut out = String::new();
        for (key, value) in self.to_map() {
            out.push_str("export ");
            out.push_str(&key);
            out.push('=');
            out.push_str(&single_quote(&value));
            out.push('\n');
        }
        out
    }

    /// Last layer wins, but the key keeps the position it first had.
    fn set(&mut self, var: EnvVar) {
        match self.vars.iter_mut().find(|existing| existing.key == var.key) {
            Some(existing) => *existing = var,
            None => self.vars.push(var),
        }
    }
}

// ---------------------------------------------------------------------------------------
// Quoting
// ---------------------------------------------------------------------------------------

/// Bytes that mean only themselves to `sh` in a value, so a value made of them alone needs no
/// quotes. Everything else — whitespace, `#`, quotes, `$`, backtick, `\`, `~`, `*`, a newline,
/// any non-ASCII byte — gets quoted rather than escaped case by case.
fn is_bare_byte(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.' | b'/' | b':' | b'@' | b'%' | b'+' | b',' | b'=')
}

fn needs_quoting(value: &str) -> bool {
    // Empty is the one special case: `KEY=` already assigns an empty string, in both `sh` and
    // every dotenv reader, and `KEY=''` only looks like a value someone forgot to fill in.
    !value.is_empty() && !value.bytes().all(is_bare_byte)
}

/// Single quotes, not double: inside double quotes `sh` still expands `$x`, `` `x` `` and `\`,
/// so `. .env.canopy` would not reproduce the value we resolved. Single quotes are literal all
/// the way through, including newlines.
fn single_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\\''"))
}

fn dotenv_value(value: &str) -> String {
    if needs_quoting(value) { single_quote(value) } else { value.to_owned() }
}

// ---------------------------------------------------------------------------------------
// Secrets
// ---------------------------------------------------------------------------------------

/// Secret by key convention first, then by credentials sitting in the value.
fn is_secret(key: &str, value: &str) -> bool {
    let upper = key.to_ascii_uppercase();
    SECRET_WORDS.iter().any(|word| upper.contains(word)) || url_with_password(value)
}

/// `scheme://user:password@host` — never printable whatever the key is called, because the
/// interesting half of a database URL is the half in the middle.
///
/// Hand-written rather than a regex: `^[a-z][a-z0-9+.-]*://[^/@\s]*:[^/@\s]+@`.
fn url_with_password(value: &str) -> bool {
    let Some((scheme, rest)) = value.split_once("://") else { return false };
    let mut scheme_bytes = scheme.bytes();
    let Some(first) = scheme_bytes.next() else { return false };
    if !first.is_ascii_alphabetic() {
        return false;
    }
    if !scheme_bytes.all(|b| b.is_ascii_alphanumeric() || matches!(b, b'+' | b'.' | b'-')) {
        return false;
    }
    // Authority ends at the first `@`; a later one (`/path/a@b`) is not userinfo.
    let Some((userinfo, _)) = rest.split_once('@') else { return false };
    if userinfo.chars().any(|c| c == '/' || c.is_whitespace()) {
        return false;
    }
    // A colon with something after it. `postgres://user@host` and `postgres://user:@host` are
    // not credentials worth hiding.
    userinfo.split_once(':').is_some_and(|(_, password)| !password.is_empty())
}

// ---------------------------------------------------------------------------------------
// Substitution
// ---------------------------------------------------------------------------------------

/// The buckets `${scope.name}` resolves against. `env` is live: a later layer can reference an
/// earlier one with `${env.name}`.
///
/// Only lowercase names are reachable, because the grammar [`template_refs`] parses — the one
/// the linter reports against, and the one the daemon's regex implements — is lowercase
/// throughout. `${env.HOME}` is therefore not a reference but shell, which is the behaviour
/// `run:` lines depend on.
type Scope = BTreeMap<String, BTreeMap<String, String>>;

/// One reference's value, or `None` to leave it written as it was.
///
/// The grammar has a third segment (`${db.main.url}`), and database forks are the scope with
/// real fields: `${db.main.file}` is a different value from `${db.main}`. A field is looked up
/// as `name.field` first. Every other bucket is flat, so there the field finds nothing and the
/// reference falls back to the name — `${worktree.path.x}` is `worktree.path`, the same
/// fallback the daemon applies.
fn lookup<'a>(scope: &'a Scope, reference: &TemplateRef) -> Option<&'a str> {
    let bucket = scope.get(&reference.scope)?;
    let dotted = reference.field.as_ref().and_then(|field| bucket.get(&format!("{}.{field}", reference.name)));
    dotted.or_else(|| bucket.get(&reference.name)).map(String::as_str)
}

/// The one `${…}` a chunk contains, if it is a reference at all.
///
/// Delegates to the linter's parser so that a reference the linter reports as unknown is
/// exactly a reference this function would have substituted — one grammar, not two that drift.
fn single_ref(chunk: &str) -> Option<TemplateRef> {
    template_refs(chunk).into_iter().next()
}

/// Replaces every resolvable `${…}` in `text`. Single-pass: the loop resumes *after* the
/// closing brace of the reference it just replaced, never inside what it inserted.
fn substitute(text: &str, scope: &Scope) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(open) = rest.find("${") {
        out.push_str(&rest[..open]);
        let candidate = &rest[open..];
        // No closing brace anywhere: the rest is shell, or a typo. Either way, verbatim.
        let Some(close) = candidate.find('}') else {
            out.push_str(candidate);
            return out;
        };
        let whole = &candidate[..=close];
        match single_ref(whole).and_then(|reference| lookup(scope, &reference)) {
            Some(value) => out.push_str(value),
            None => out.push_str(whole),
        }
        rest = &candidate[close + 1..];
    }
    out.push_str(rest);
    out
}

/// `main-db` → `MAIN_DB`: the shape every generated env key uses.
pub(crate) fn upper_snake(name: &str) -> String {
    let mut out = String::with_capacity(name.len());
    let mut in_separator = false;
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch.to_ascii_uppercase());
            in_separator = false;
        } else if !in_separator {
            // A run of separators collapses: `main--db` is one boundary, not two.
            out.push('_');
            in_separator = true;
        }
    }
    out
}

// ---------------------------------------------------------------------------------------
// Resolution
// ---------------------------------------------------------------------------------------

/// What this worktree is, for the Canopy variables and the `${…}` scopes.
///
/// Borrowed rather than owned: the caller already has all of it, and copying it per service
/// would be the only allocation in the hot path.
#[derive(Debug, Clone, Copy)]
pub struct Facts<'a> {
    pub worktree_name: &'a str,
    pub worktree_path: &'a Utf8Path,
    /// Empty when the worktree is on a detached HEAD.
    pub branch: &'a str,
    pub project: &'a str,
    pub project_path: &'a Utf8Path,
    /// Named port → the number allocated to this worktree.
    pub ports: &'a BTreeMap<String, u16>,
    /// This worktree's database forks: only the ones that are there. A recorded fork that has
    /// gone missing is left out, so nothing is pointed at a database that does not exist.
    pub databases: &'a [crate::db::DbInstance],
}

/// The project-wide environment: Canopy's facts, `defaults.env`, `env:`, then the caller's
/// overrides. Last layer wins.
pub fn resolve(config: &CanopyConfig, facts: &Facts<'_>, overrides: &BTreeMap<String, String>) -> EnvTable {
    let mut resolver = Resolver::new(facts);
    resolver.layers(config, overrides);
    resolver.table
}

/// The environment one service sees: [`resolve`] with the service's own `env:` on top.
///
/// `None` when the config has no such service — a caller asking for a name that is not there
/// has a different problem than a service with nothing set.
pub fn resolve_service(
    config: &CanopyConfig,
    service: &str,
    facts: &Facts<'_>,
    overrides: &BTreeMap<String, String>,
) -> Option<EnvTable> {
    let spec = config.services.get(service)?;
    let mut resolver = Resolver::new(facts);
    resolver.layers(config, overrides);
    resolver.layer(&spec.env, EnvSource::Service);
    Some(resolver.table)
}

/// Renders `${…}` in arbitrary text — a `run:` command, a health URL, a setup step — against
/// the same scope that produced `table`, so a command and the environment it runs in cannot
/// disagree about what `${ports.web}` means.
pub fn interpolate(text: &str, facts: &Facts<'_>, table: &EnvTable) -> String {
    let mut resolver = Resolver::new(facts);
    resolver.scope.insert("env".to_owned(), table.to_map());
    substitute(text, &resolver.scope)
}

/// Carries the scope alongside the table being built, since each layer is substituted against
/// everything resolved before it.
struct Resolver<'a> {
    scope: Scope,
    table: EnvTable,
    facts: &'a Facts<'a>,
}

impl<'a> Resolver<'a> {
    fn new(facts: &'a Facts<'a>) -> Resolver<'a> {
        let ports = facts.ports.iter().map(|(name, port)| (name.clone(), port.to_string())).collect();
        let worktree = BTreeMap::from([
            ("name".to_owned(), facts.worktree_name.to_owned()),
            ("path".to_owned(), facts.worktree_path.to_string()),
            ("branch".to_owned(), facts.branch.to_owned()),
        ]);
        let project = BTreeMap::from([
            ("name".to_owned(), facts.project.to_owned()),
            ("path".to_owned(), facts.project_path.to_string()),
        ]);
        // `${db.main}` and `${db.main.url}` are the URL; every other field is `${db.main.<field>}`.
        // A database with no fork has no entry, so a reference to it stays visible as written
        // instead of becoming an empty string.
        let mut db = BTreeMap::new();
        for instance in facts.databases {
            db.insert(instance.name.clone(), instance.url.clone());
            for (field, value) in instance.fields() {
                db.insert(format!("{}.{field}", instance.name), value);
            }
        }
        let scope = Scope::from([
            ("ports".to_owned(), ports),
            ("db".to_owned(), db),
            ("worktree".to_owned(), worktree),
            ("project".to_owned(), project),
            ("env".to_owned(), BTreeMap::new()),
        ]);
        Resolver { scope, table: EnvTable::default(), facts }
    }

    fn layers(&mut self, config: &CanopyConfig, overrides: &BTreeMap<String, String>) {
        self.canopy_facts();
        self.layer(&config.defaults.env, EnvSource::Defaults);
        self.layer(&config.env, EnvSource::Config);
        // After the file, so a fork's URL is what `DATABASE_URL` means even when the file sets a
        // shared one for people who run without canopyd. Before the overrides, because a caller
        // who names a URL explicitly has decided.
        for instance in self.facts.databases {
            self.record(&instance.env_key, instance.url.clone(), EnvSource::Database);
        }
        self.layer(overrides, EnvSource::Override);
    }

    /// Always present, always overridable by the project: a file that wants `CANOPY_BRANCH` to
    /// mean something else is allowed to say so.
    fn canopy_facts(&mut self) {
        let facts = self.facts;
        let named = [
            ("CANOPY_WORKTREE", facts.worktree_name.to_owned()),
            ("CANOPY_WORKTREE_PATH", facts.worktree_path.to_string()),
            ("CANOPY_BRANCH", facts.branch.to_owned()),
            ("CANOPY_PROJECT", facts.project.to_owned()),
        ];
        // Facts are data, not templates: a branch named `wip/${ports.web}` must arrive in
        // `CANOPY_BRANCH` exactly as git spells it.
        for (key, value) in named {
            self.record(key, value, EnvSource::Canopy);
        }
        for (name, port) in facts.ports {
            self.record(&format!("CANOPY_PORT_{}", upper_snake(name)), port.to_string(), EnvSource::Canopy);
        }
        for instance in facts.databases {
            let key = format!("CANOPY_DB_{}_URL", upper_snake(&instance.name));
            self.record(&key, instance.url.clone(), EnvSource::Canopy);
        }
    }

    fn layer(&mut self, map: &BTreeMap<String, String>, source: EnvSource) {
        for (key, raw) in map {
            let value = substitute(raw, &self.scope);
            self.record(key, value, source);
        }
    }

    fn record(&mut self, key: &str, value: String, source: EnvSource) {
        let secret = is_secret(key, &value);
        self.scope.entry("env".to_owned()).or_default().insert(key.to_owned(), value.clone());
        self.table.set(EnvVar { key: key.to_owned(), value, secret, source });
    }
}

// ---------------------------------------------------------------------------------------
// Writing
// ---------------------------------------------------------------------------------------

/// Writes the dotenv `env_file:` names, and returns where it went.
///
/// `Ok(None)` means `env_file: false` — nothing was written and nothing went wrong. A relative
/// path resolves inside the worktree, which is the only place a generated file belongs.
pub fn write_env_file(
    config: &CanopyConfig,
    worktree: &Utf8Path,
    table: &EnvTable,
) -> Result<Option<Utf8PathBuf>, EnvError> {
    let Some(relative) = config.env_file.path() else { return Ok(None) };
    let path = worktree.join(relative);
    // `env_file: config/.env` is legal, and the directory may not exist in a fresh worktree.
    let parent = path.parent().unwrap_or(worktree);
    fs::create_dir_all(parent).map_err(|source| EnvError::Write { path: path.clone(), source })?;
    fs::write(&path, table.to_dotenv()).map_err(|source| EnvError::Write { path: path.clone(), source })?;
    Ok(Some(path))
}

#[cfg(test)]
mod tests {
    use std::process::Command;

    use rstest::rstest;
    use serde_json::json;
    use tempfile::TempDir;

    use super::*;

    // -----------------------------------------------------------------------------------
    // Helpers
    // -----------------------------------------------------------------------------------

    /// A config built from JSON rather than YAML: these tests are about resolution, and a
    /// fixture that has to survive the linter (which rejects `${ports.nope}`) could not express
    /// half of what resolution has to cope with.
    fn config(value: serde_json::Value) -> CanopyConfig {
        serde_json::from_value(value).expect("test config")
    }

    fn bare_config() -> CanopyConfig {
        config(json!({ "version": 1 }))
    }

    /// Owns what [`Facts`] borrows.
    struct Fixture {
        name: String,
        path: Utf8PathBuf,
        branch: String,
        project: String,
        project_path: Utf8PathBuf,
        ports: BTreeMap<String, u16>,
    }

    impl Fixture {
        fn new() -> Fixture {
            Fixture {
                name: "canopy.feature-x".to_owned(),
                path: Utf8PathBuf::from("/src/canopy.feature-x"),
                branch: "feature/x".to_owned(),
                project: "canopy".to_owned(),
                project_path: Utf8PathBuf::from("/src/canopy"),
                ports: BTreeMap::from([("web".to_owned(), 3000), ("main-db".to_owned(), 5433)]),
            }
        }

        fn facts(&self) -> Facts<'_> {
            Facts {
                worktree_name: &self.name,
                worktree_path: &self.path,
                branch: &self.branch,
                project: &self.project,
                project_path: &self.project_path,
                ports: &self.ports,
                databases: &[],
            }
        }
    }

    fn overrides(pairs: &[(&str, &str)]) -> BTreeMap<String, String> {
        pairs.iter().map(|(key, value)| ((*key).to_owned(), (*value).to_owned())).collect()
    }

    /// A table with these values verbatim — no substitution, so a quoting test can use a value
    /// that looks like a template.
    fn table_of(pairs: &[(&str, &str)]) -> EnvTable {
        let mut table = EnvTable::default();
        for (key, value) in pairs {
            table.set(EnvVar {
                key: (*key).to_owned(),
                value: (*value).to_owned(),
                secret: is_secret(key, value),
                source: EnvSource::Override,
            });
        }
        table
    }

    /// Resolves `env:` values against the standard fixture and returns the table.
    fn resolved(env: serde_json::Value) -> EnvTable {
        let fixture = Fixture::new();
        resolve(&config(json!({ "version": 1, "env": env })), &fixture.facts(), &BTreeMap::new())
    }

    fn value_of(env: serde_json::Value, key: &str) -> String {
        resolved(env).get(key).expect("key present").to_owned()
    }

    fn temp() -> (TempDir, Utf8PathBuf) {
        let dir = TempDir::new().expect("tempdir");
        let path = Utf8PathBuf::from_path_buf(dir.path().to_path_buf()).expect("utf-8 tempdir");
        (dir, path)
    }

    /// What `sh` sees after sourcing `file` — the only assertion that proves our quoting is
    /// right, since the file exists to be read by a shell and not by us.
    fn sh_value(file: &Utf8Path, key: &str) -> String {
        let script = format!("set -a; . \"$1\"; printf %s \"${{{key}}}\"");
        let output =
            Command::new("/bin/sh").arg("-c").arg(script).arg("sh").arg(file.as_str()).output().expect("run /bin/sh");
        assert!(output.status.success(), "sh failed: {}", String::from_utf8_lossy(&output.stderr));
        String::from_utf8(output.stdout).expect("utf-8 from sh")
    }

    /// Every value a dotenv has to survive, once, so the quoting rule is stated in one place.
    const AWKWARD: &[&str] = &[
        "plain",
        "with spaces",
        "trailing#hash",
        "double\"quote",
        "single'quote",
        "both\"and'quotes",
        "dollar$HOME and ${braces}",
        "back`tick`",
        "back\\slash",
        "semi;colon & amp | pipe",
        "line\nbreak",
        "trailing\n",
        "",
        "  padded  ",
        "café ✓ 日本語",
        "a=b,c:d/e@f%g+h.i-j_k",
        "*glob?",
        "~/tilde",
    ];

    // -----------------------------------------------------------------------------------
    // Interpolation
    // -----------------------------------------------------------------------------------

    #[test]
    fn resolves_every_scope() {
        let table = resolved(json!({
            "a_port": "http://127.0.0.1:${ports.web}/",
            "b_name": "${worktree.name}",
            "c_path": "${worktree.path}",
            "d_branch": "${worktree.branch}",
            "e_project": "${project.name}",
            "f_project_path": "${project.path}",
            "g_env": "port ${env.a_port} of ${env.e_project}",
        }));
        assert_eq!(table.get("a_port"), Some("http://127.0.0.1:3000/"));
        assert_eq!(table.get("b_name"), Some("canopy.feature-x"));
        assert_eq!(table.get("c_path"), Some("/src/canopy.feature-x"));
        assert_eq!(table.get("d_branch"), Some("feature/x"));
        assert_eq!(table.get("e_project"), Some("canopy"));
        assert_eq!(table.get("f_project_path"), Some("/src/canopy"));
        // Layered alphabetically, so a_port and e_project are already resolved when g_env is.
        assert_eq!(table.get("g_env"), Some("port http://127.0.0.1:3000/ of canopy"));
    }

    #[test]
    fn resolves_several_references_in_one_value() {
        assert_eq!(
            value_of(json!({ "A": "${ports.web}:${ports.main-db}:${project.name}!" }), "A"),
            "3000:5433:canopy!"
        );
    }

    #[rstest]
    // A scope we do not have. Databases are declared in the file and forked by the daemon; a
    // worktree run by this crate has none, and blanking the URL would produce a connection
    // string that fails somewhere far from here.
    #[case("${db.main.url}")]
    #[case("${db.main}")]
    // A port nobody allocated — a typo the linter already reports; resolution does not also
    // have to punish it.
    #[case("${ports.nope}")]
    #[case("${cache.redis}")]
    // Shell, not a template. `run:` goes to `/bin/sh -c`, so both of these must survive.
    #[case("${CANOPY_HOME}")]
    #[case("$(cat /etc/passwd)")]
    #[case("$HOME/bin")]
    // Shaped like a reference but outside the grammar: one segment, four segments, an
    // uppercase *resource* name. Ports, databases and services follow the lowercase naming
    // rule, so `${ports.WEB}` names something that cannot exist and stays literal.
    #[case("${ports.WEB}")]
    // An env name that is not a shell variable name.
    #[case("${env.9lives}")]
    #[case("${env.my-var}")]
    #[case("${web}")]
    #[case("${a.b.c.d}")]
    #[case("${}")]
    #[case("${.}")]
    // Never closed.
    #[case("${ports.web")]
    #[case("cost: 100${")]
    fn leaves_unresolvable_text_verbatim(#[case] raw: &str) {
        assert_eq!(value_of(json!({ "A": raw }), "A"), raw);
    }

    #[test]
    fn an_env_reference_resolves_against_the_table_being_built() {
        // Uppercase is the whole point of the `env` scope: variable names are uppercase by
        // convention, and `${env.HOME}` is what anyone would write.
        assert_eq!(value_of(json!({ "A": "${env.CANOPY_PORT_WEB}" }), "A"), "3000");
        assert_eq!(value_of(json!({ "A": "x", "B": "${env.A}!" }), "B"), "x!");
    }

    #[test]
    fn an_env_reference_to_something_undefined_stays_verbatim() {
        // The variable may be coming from the surrounding shell, which `run:` can still see.
        assert_eq!(value_of(json!({ "A": "${env.NOT_SET_ANYWHERE}" }), "A"), "${env.NOT_SET_ANYWHERE}");
    }

    #[test]
    fn keeps_the_text_around_a_reference() {
        assert_eq!(value_of(json!({ "A": "before ${ports.web} after" }), "A"), "before 3000 after");
        assert_eq!(value_of(json!({ "A": "${ports.nope} then ${ports.web}" }), "A"), "${ports.nope} then 3000");
        assert_eq!(value_of(json!({ "A": "${ports.web} then ${ports.nope}" }), "A"), "3000 then ${ports.nope}");
        assert_eq!(value_of(json!({ "A": "" }), "A"), "");
    }

    #[test]
    fn a_field_refines_nothing_yet() {
        // Falls back to the two-segment value, as the daemon does.
        assert_eq!(value_of(json!({ "A": "${ports.web.number}" }), "A"), "3000");
    }

    #[test]
    fn substitution_is_single_pass() {
        let mut fixture = Fixture::new();
        // A perfectly legal branch name that is also a template.
        fixture.branch = "wip/${ports.web}".to_owned();
        let table = resolve(
            &config(json!({ "version": 1, "env": { "a_branch": "${worktree.branch}" } })),
            &fixture.facts(),
            &overrides(&[("b_again", "${env.a_branch}")]),
        );
        // Rescanning would turn a branch name into a port number here, and a `${db.x.url}` in
        // a branch name into someone's credentials.
        assert_eq!(table.get("a_branch"), Some("wip/${ports.web}"));
        assert_eq!(table.get("b_again"), Some("wip/${ports.web}"));
        // And the fact itself is data, never a template.
        assert_eq!(table.get("CANOPY_BRANCH"), Some("wip/${ports.web}"));
    }

    #[test]
    fn interpolates_arbitrary_text_against_the_table() {
        let fixture = Fixture::new();
        let table = resolve(
            &config(json!({ "version": 1, "env": { "host": "127.0.0.1" } })),
            &fixture.facts(),
            &BTreeMap::new(),
        );
        assert_eq!(
            interpolate("vite --host ${env.host} --port ${ports.web} # ${nope.x}", &fixture.facts(), &table),
            "vite --host 127.0.0.1 --port 3000 # ${nope.x}"
        );
    }

    #[rstest]
    #[case("web", "WEB")]
    #[case("main-db", "MAIN_DB")]
    #[case("main--db", "MAIN_DB")]
    #[case("a-b-c", "A_B_C")]
    #[case("Web2", "WEB2")]
    #[case("a.b c", "A_B_C")]
    #[case("-lead", "_LEAD")]
    #[case("", "")]
    fn upper_snakes_names(#[case] input: &str, #[case] expected: &str) {
        assert_eq!(upper_snake(input), expected);
    }

    // -----------------------------------------------------------------------------------
    // Layering
    // -----------------------------------------------------------------------------------

    #[test]
    fn each_layer_overrides_the_one_before() {
        let fixture = Fixture::new();
        let facts = fixture.facts();
        let canopy_only = config(json!({ "version": 1 }));
        let with_defaults = config(json!({ "version": 1, "defaults": { "env": { "K": "defaults" } } }));
        let with_env = config(json!({
            "version": 1,
            "defaults": { "env": { "K": "defaults" } },
            "env": { "K": "config" },
        }));
        let with_service = config(json!({
            "version": 1,
            "defaults": { "env": { "K": "defaults" } },
            "env": { "K": "config" },
            "services": { "web": { "run": "true", "env": { "K": "service" } } },
        }));
        let override_k = overrides(&[("K", "override")]);

        assert_eq!(resolve(&canopy_only, &facts, &BTreeMap::new()).get("K"), None);
        assert_eq!(resolve(&with_defaults, &facts, &BTreeMap::new()).get("K"), Some("defaults"));
        assert_eq!(resolve(&with_env, &facts, &BTreeMap::new()).get("K"), Some("config"));
        assert_eq!(resolve(&with_env, &facts, &override_k).get("K"), Some("override"));
        assert_eq!(resolve_service(&with_service, "web", &facts, &BTreeMap::new()).unwrap().get("K"), Some("service"));
        // The service has the last word even over an override.
        assert_eq!(resolve_service(&with_service, "web", &facts, &override_k).unwrap().get("K"), Some("service"));
    }

    #[test]
    fn every_layer_is_tagged_with_where_it_came_from() {
        let fixture = Fixture::new();
        let table = resolve_service(
            &config(json!({
                "version": 1,
                "defaults": { "env": { "D": "d" } },
                "env": { "C": "c" },
                "services": { "web": { "run": "true", "env": { "S": "s" } } },
            })),
            "web",
            &fixture.facts(),
            &overrides(&[("O", "o")]),
        )
        .expect("service");
        let sources: BTreeMap<String, EnvSource> =
            table.vars().iter().map(|var| (var.key.clone(), var.source)).collect();
        assert_eq!(sources["CANOPY_WORKTREE"], EnvSource::Canopy);
        assert_eq!(sources["D"], EnvSource::Defaults);
        assert_eq!(sources["C"], EnvSource::Config);
        assert_eq!(sources["O"], EnvSource::Override);
        assert_eq!(sources["S"], EnvSource::Service);
    }

    #[test]
    fn an_overridden_key_keeps_its_place_and_its_new_source() {
        let fixture = Fixture::new();
        let table = resolve(
            &config(json!({ "version": 1, "env": { "CANOPY_WORKTREE": "renamed" } })),
            &fixture.facts(),
            &BTreeMap::new(),
        );
        assert_eq!(table.vars()[0].key, "CANOPY_WORKTREE");
        assert_eq!(table.vars()[0].value, "renamed");
        assert_eq!(table.vars()[0].source, EnvSource::Config);
        assert_eq!(table.vars().iter().filter(|var| var.key == "CANOPY_WORKTREE").count(), 1);
    }

    #[test]
    fn a_later_layer_sees_an_earlier_one() {
        let fixture = Fixture::new();
        let table = resolve(
            &config(
                json!({ "version": 1, "defaults": { "env": { "base": "/srv" } }, "env": { "sub": "${env.base}/x" } }),
            ),
            &fixture.facts(),
            &overrides(&[("deep", "${env.sub}/y")]),
        );
        assert_eq!(table.get("sub"), Some("/srv/x"));
        assert_eq!(table.get("deep"), Some("/srv/x/y"));
    }

    // -----------------------------------------------------------------------------------
    // Canopy's own facts
    // -----------------------------------------------------------------------------------

    #[test]
    fn states_the_canopy_facts() {
        let fixture = Fixture::new();
        let table = resolve(&bare_config(), &fixture.facts(), &BTreeMap::new());
        assert_eq!(table.get("CANOPY_WORKTREE"), Some("canopy.feature-x"));
        assert_eq!(table.get("CANOPY_WORKTREE_PATH"), Some("/src/canopy.feature-x"));
        assert_eq!(table.get("CANOPY_BRANCH"), Some("feature/x"));
        assert_eq!(table.get("CANOPY_PROJECT"), Some("canopy"));
        assert_eq!(table.get("CANOPY_PORT_WEB"), Some("3000"));
        // `main-db` is not a legal env key; the generated one is.
        assert_eq!(table.get("CANOPY_PORT_MAIN_DB"), Some("5433"));
        assert_eq!(table.get("CANOPY_PORT_main-db"), None);
        assert_eq!(table.vars().len(), 6);
    }

    #[test]
    fn a_detached_head_has_an_empty_branch() {
        let mut fixture = Fixture::new();
        fixture.branch = String::new();
        fixture.ports = BTreeMap::new();
        let table = resolve(&bare_config(), &fixture.facts(), &BTreeMap::new());
        assert_eq!(table.get("CANOPY_BRANCH"), Some(""));
        assert_eq!(table.vars().len(), 4);
    }

    // -----------------------------------------------------------------------------------
    // Services
    // -----------------------------------------------------------------------------------

    #[test]
    fn a_service_layers_over_the_project() {
        let fixture = Fixture::new();
        let config = config(json!({
            "version": 1,
            "env": { "SHARED": "project", "only_project": "yes" },
            "services": {
                "web": { "run": "true", "env": { "SHARED": "web", "PORT": "${ports.web}", "FROM_ENV": "${env.only_project}" } },
                "api": { "run": "true" },
            },
        }));
        let web = resolve_service(&config, "web", &fixture.facts(), &BTreeMap::new()).expect("web");
        assert_eq!(web.get("SHARED"), Some("web"));
        assert_eq!(web.get("only_project"), Some("yes"));
        assert_eq!(web.get("PORT"), Some("3000"));
        assert_eq!(web.get("FROM_ENV"), Some("yes"));

        // A service with no env of its own is the project table exactly.
        let api = resolve_service(&config, "api", &fixture.facts(), &BTreeMap::new()).expect("api");
        assert_eq!(api, resolve(&config, &fixture.facts(), &BTreeMap::new()));
        assert_eq!(api.get("SHARED"), Some("project"));
    }

    #[test]
    fn an_unknown_service_is_none() {
        let fixture = Fixture::new();
        let config = config(json!({ "version": 1, "services": { "web": { "run": "true" } } }));
        assert!(resolve_service(&config, "web", &fixture.facts(), &BTreeMap::new()).is_some());
        assert!(resolve_service(&config, "worker", &fixture.facts(), &BTreeMap::new()).is_none());
    }

    // -----------------------------------------------------------------------------------
    // Secrets
    // -----------------------------------------------------------------------------------

    #[rstest]
    #[case("API_SECRET", "x", true)]
    #[case("GITHUB_TOKEN", "x", true)]
    #[case("DB_PASSWORD", "x", true)]
    #[case("PGPASSWD", "x", true)]
    #[case("APIKEY", "x", true)]
    #[case("MY_API_KEY", "x", true)]
    #[case("PRIVATE_KEY", "x", true)]
    #[case("AWS_CREDENTIAL_FILE", "x", true)]
    // Case-insensitive on the key.
    #[case("stripe_secret", "x", true)]
    // Not a word we treat as sensitive, and a value with nothing in it.
    #[case("NODE_ENV", "development", false)]
    #[case("KEY_LAYOUT", "dvorak", false)]
    #[case("PUBLIC_URL", "https://example.com/", false)]
    // The value, whatever the key is called.
    #[case("DATABASE_URL", "postgres://app:hunter2@localhost:5432/db", true)]
    #[case("DATABASE_URL", "postgres://app@localhost:5432/db", false)]
    #[case("DATABASE_URL", "postgres://app:@localhost:5432/db", false)]
    #[case("DATABASE_URL", "postgres://localhost:5432/db", false)]
    #[case("MIXED", "POSTGRES://app:pw@host/db", true)]
    #[case("SCHEME", "1postgres://app:pw@host/db", false)]
    #[case("SCHEME", "post gres://app:pw@host/db", false)]
    #[case("SCHEME", "post+gres.v2-x://app:pw@host/db", true)]
    #[case("SCHEME", "://app:pw@host/db", false)]
    #[case("NOT_A_URL", "user:pw@host", false)]
    #[case("PATH_AT", "https://example.com/a:b@c", false)]
    #[case("SPACED", "https://us er:pw@host", false)]
    #[case("EMPTY", "", false)]
    fn spots_a_secret(#[case] key: &str, #[case] value: &str, #[case] expected: bool) {
        assert_eq!(is_secret(key, value), expected, "{key}={value}");
    }

    #[test]
    fn masking_is_presentation_only() {
        let table = table_of(&[("NODE_ENV", "development"), ("API_TOKEN", "t0ken"), ("DB", "mysql://u:p@h/d")]);
        let masked = table.masked();
        assert_eq!(masked[0].value, "development");
        assert_eq!(masked[1].value, MASK);
        assert_eq!(masked[2].value, MASK);
        assert_eq!(masked[1].key, "API_TOKEN");
        assert!(masked[1].secret);
        assert!(!masked[0].secret);

        // Everything a process actually reads keeps the real value.
        assert_eq!(table.get("API_TOKEN"), Some("t0ken"));
        assert_eq!(table.to_map()["API_TOKEN"], "t0ken");
        assert!(table.to_dotenv().contains("API_TOKEN=t0ken"));
        assert!(table.to_export().contains("export API_TOKEN='t0ken'"));
        assert!(!table.to_dotenv().contains(MASK));
        assert!(!table.to_export().contains(MASK));

        // A mask that is not the value's length; the length is a secret too.
        assert_eq!(MASK.len(), 8);
        let long = table_of(&[("API_TOKEN", "a-very-long-token-indeed")]);
        assert_eq!(long.masked()[0].value, MASK);
    }

    #[test]
    fn masking_survives_serialization() {
        let table = table_of(&[("API_TOKEN", "t0ken")]);
        let json = serde_json::to_string(&table.masked()).expect("json");
        assert_eq!(json, r#"[{"key":"API_TOKEN","value":"********","secret":true,"source":"override"}]"#);
        assert!(serde_json::to_string(&table).expect("json").contains("t0ken"));
    }

    #[test]
    fn a_resolved_value_can_become_a_secret() {
        let fixture = Fixture::new();
        // The key says nothing; the resolved value does.
        let table = resolve(
            &config(json!({ "version": 1, "env": { "MAIN": "postgres://app:pw@127.0.0.1:${ports.main-db}/app" } })),
            &fixture.facts(),
            &BTreeMap::new(),
        );
        assert_eq!(table.get("MAIN"), Some("postgres://app:pw@127.0.0.1:5433/app"));
        assert!(table.vars().iter().find(|var| var.key == "MAIN").expect("MAIN").secret);
    }

    // -----------------------------------------------------------------------------------
    // The table itself
    // -----------------------------------------------------------------------------------

    #[test]
    fn reads_back_what_it_holds() {
        let table = table_of(&[("B", "2"), ("A", "1"), ("B", "3")]);
        assert_eq!(table.get("B"), Some("3"));
        assert_eq!(table.get("A"), Some("1"));
        assert_eq!(table.get("MISSING"), None);
        assert_eq!(table.get("b"), None);
        // Insertion order for the list, sorted for the map.
        assert_eq!(table.vars().iter().map(|var| var.key.as_str()).collect::<Vec<_>>(), ["B", "A"]);
        assert_eq!(table.vars().len(), 2);
        assert_eq!(
            table.to_map(),
            BTreeMap::from([("A".to_owned(), "1".to_owned()), ("B".to_owned(), "3".to_owned())])
        );
        assert_eq!(EnvTable::default().vars(), &[]);
        assert_eq!(EnvTable::default().get("A"), None);
    }

    // -----------------------------------------------------------------------------------
    // Dotenv text
    // -----------------------------------------------------------------------------------

    #[test]
    fn quotes_only_what_needs_it() {
        let table = table_of(&[
            ("BARE", "postgres://localhost:5432/db"),
            ("EMPTY", ""),
            ("SPACED", "two words"),
            ("HASH", "a#b"),
            ("SINGLE", "it's"),
        ]);
        assert_eq!(
            table.to_dotenv(),
            concat!(
                "# generated by canopy — do not edit\n",
                "BARE=postgres://localhost:5432/db\n",
                "EMPTY=\n",
                "HASH='a#b'\n",
                "SINGLE='it'\\''s'\n",
                "SPACED='two words'\n",
            )
        );
    }

    #[rstest]
    #[case("plain", false)]
    #[case("a-b_c.d/e:f@g%h+i,j=k9", false)]
    #[case("", false)]
    #[case(" ", true)]
    #[case("a b", true)]
    #[case("a\tb", true)]
    #[case(" lead", true)]
    #[case("trail ", true)]
    #[case("a#b", true)]
    #[case("a\"b", true)]
    #[case("a'b", true)]
    #[case("a$b", true)]
    #[case("a`b", true)]
    #[case("a\\b", true)]
    #[case("a\nb", true)]
    #[case("café", true)]
    #[case("a*b", true)]
    #[case("~b", true)]
    fn knows_when_a_value_needs_quoting(#[case] value: &str, #[case] expected: bool) {
        assert_eq!(needs_quoting(value), expected, "{value:?}");
    }

    #[test]
    fn sorts_and_repeats_itself() {
        let one = table_of(&[("Z", "z"), ("A", "a"), ("M", "m")]);
        let other = table_of(&[("M", "m"), ("Z", "z"), ("A", "a")]);
        assert_eq!(one.to_dotenv(), other.to_dotenv());
        assert_eq!(one.to_dotenv(), one.to_dotenv());
        let text = one.to_dotenv();
        let keys: Vec<&str> = text.lines().skip(1).map(|line| line.split('=').next().unwrap()).collect();
        assert_eq!(keys, ["A", "M", "Z"]);
        assert_eq!(one.to_dotenv().lines().next(), Some("# generated by canopy — do not edit"));
    }

    #[rstest]
    fn a_shell_reads_back_exactly_what_we_resolved(#[values(true, false)] export: bool) {
        let (_dir, dir) = temp();
        for (index, value) in AWKWARD.iter().enumerate() {
            let table = table_of(&[("K", value)]);
            let file = dir.join(format!("file{index}"));
            let text = if export { table.to_export() } else { table.to_dotenv() };
            fs::write(&file, &text).expect("write");
            assert_eq!(&sh_value(&file, "K"), value, "{text:?}");
        }
    }

    #[test]
    fn a_shell_reads_back_a_whole_table() {
        let (_dir, dir) = temp();
        let table = table_of(&[("A", "one two"), ("B", "$A"), ("C", "")]);
        let file = dir.join(".env.canopy");
        fs::write(&file, table.to_dotenv()).expect("write");
        assert_eq!(sh_value(&file, "A"), "one two");
        // `$A` is a value, not a reference: nothing expands it on the way back in.
        assert_eq!(sh_value(&file, "B"), "$A");
        assert_eq!(sh_value(&file, "C"), "");
    }

    #[test]
    fn export_lines_are_exports() {
        let table = table_of(&[("A", "one two"), ("B", "")]);
        assert_eq!(table.to_export(), "export A='one two'\nexport B=''\n");
        assert_eq!(EnvTable::default().to_export(), "");
        assert_eq!(EnvTable::default().to_dotenv(), "# generated by canopy — do not edit\n");
    }

    // -----------------------------------------------------------------------------------
    // Writing
    // -----------------------------------------------------------------------------------

    #[test]
    fn writes_where_env_file_says() {
        let (_dir, worktree) = temp();
        let table = table_of(&[("A", "1")]);
        let path = write_env_file(&bare_config(), &worktree, &table).expect("write").expect("a path");
        assert_eq!(path, worktree.join(".env.canopy"));
        assert_eq!(fs::read_to_string(&path).expect("read"), table.to_dotenv());

        // A named path, in a directory that does not exist yet.
        let config = config(json!({ "version": 1, "env_file": "config/local/.env" }));
        let nested = write_env_file(&config, &worktree, &table).expect("write").expect("a path");
        assert_eq!(nested, worktree.join("config/local/.env"));
        assert!(nested.exists());
    }

    #[test]
    fn writing_twice_is_byte_identical() {
        let (_dir, worktree) = temp();
        let fixture = Fixture::new();
        let table = resolve(
            &config(json!({ "version": 1, "defaults": { "env": { "Z": "last" } }, "env": { "A": "${ports.web}" } })),
            &fixture.facts(),
            &overrides(&[("M", "a b c")]),
        );
        let path = write_env_file(&bare_config(), &worktree, &table).expect("write").expect("a path");
        let first = fs::read(&path).expect("read");
        write_env_file(&bare_config(), &worktree, &table).expect("write");
        assert_eq!(fs::read(&path).expect("read"), first);
        assert!(!first.is_empty());
    }

    #[test]
    fn env_file_false_writes_nothing() {
        let (_dir, worktree) = temp();
        let config = config(json!({ "version": 1, "env_file": false }));
        assert_eq!(write_env_file(&config, &worktree, &table_of(&[("A", "1")])).expect("ok"), None);
        assert_eq!(fs::read_dir(worktree.as_std_path()).expect("read dir").count(), 0);
    }

    #[test]
    fn a_write_that_cannot_happen_says_where() {
        let (_dir, worktree) = temp();
        fs::write(worktree.join("config"), "i am a file").expect("write");
        let config = config(json!({ "version": 1, "env_file": "config/.env" }));
        let error = write_env_file(&config, &worktree, &table_of(&[("A", "1")])).expect_err("a file is not a dir");
        assert!(error.to_string().starts_with(&format!("cannot write {worktree}/config/.env: ")), "{error}");
    }
}
